/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Administrativo;
import java.awt.ItemSelectable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parsingDB.*;
import Models.*;
import Utils.*;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author User
 */
public class frmUsuarios extends javax.swing.JFrame {

    txtParsing txtParsing1;
    int totalAdmin = 0;
    int totalSec = 0;

    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtParsing1 = new txtParsing("adm");
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDescCat = new javax.swing.JLabel();
        txtIdent = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        lblDescCat1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblDescCat2 = new javax.swing.JLabel();
        lblDescCat3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        cmbDepen = new javax.swing.JComboBox();
        cmbTipo = new javax.swing.JComboBox();
        btnClean1 = new javax.swing.JButton();
        btnClean2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gestión de Usuarios");

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Usuario"));

        lblDescCat.setText("Identificación*:");

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClean.setText("Limpiar");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        lblDescCat1.setText("Tipo*:");

        lblNombre.setText("Nombres *:");

        lblDescCat2.setText("Password*:");

        lblDescCat3.setText("Dependencia*:");

        txtPass.setText("jPasswordField1");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        btnClean1.setText("Actualizar");
        btnClean1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClean1ActionPerformed(evt);
            }
        });

        btnClean2.setText("Eliminar");
        btnClean2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClean2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescCat)
                    .addComponent(lblDescCat1)
                    .addComponent(lblNombre)
                    .addComponent(lblDescCat2)
                    .addComponent(lblDescCat3))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdent)
                    .addComponent(txtNombres)
                    .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbDepen, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClean1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnClean2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescCat)
                            .addComponent(txtIdent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblDescCat1)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescCat2)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescCat3)
                            .addComponent(cmbDepen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClean)
                    .addComponent(btnClean1)
                    .addComponent(btnClean2))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(435, 435, 435)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initialize() {
        this.txtNombres.setText("");
        this.txtIdent.setText("");
        this.txtPass.setText("");
        fillTableCat();
        formatCatalogos();
    }

    public void fillTableCat() {
        totalAdmin = 0;
        totalSec = 0;
        try {
            Object columnas[] = {"Nombres", "Identificacion", "Tipo", "Dependencia"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);

            DefaultTableModel oldModel = (DefaultTableModel) tblUsers.getModel();
            //oldModel.setRowCount(0);
            String name = oldModel.getColumnName(1);
            if (name.equals("Title 2")) {
                tblUsers.setModel(modelo);
                for (Administrativo objUsr : txtParsing1.lstAdministrativosObj) {
                    String nombres = String.valueOf(objUsr.getStrNombres());
                    String identificacion = String.valueOf(objUsr.getStrIdentificacion());
                    String tipo = objUsr.getChrTipo();
                    String tipoString = tipo.equals("1") ? "Administrador" : "Secretaria";
                    String dependencia = String.valueOf(objUsr.getStrDependencia());
                    String modeloTemp[] = {nombres, identificacion, tipoString, dependencia};
                    modelo.addRow(modeloTemp);
                    if (Integer.parseInt(tipo) == 1) {
                        totalAdmin++;
                    } else {
                        totalSec++;
                    }
                }
                this.pack();
            } else {
                String nombres = "asd";
                String identificacion = "asd";
                String tipoString = "asd";
                String dependencia = "asd";
                String modeloTemp[] = {nombres, identificacion, tipoString, dependencia};
                modelo.addRow(modeloTemp);
                this.pack();
                modelo.fireTableDataChanged();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.toString());
        }
    }

    public void formatCatalogos() {
        this.cmbTipo.addItem("Administrador");
        this.cmbTipo.addItem("Secreataria");
        for (ItemCatalogo icat : txtParsing1.lstItemsCatalogosObj) {
            if (icat.getIdCatalogo().equals("Depencias")) {
                this.cmbDepen.addItem(icat.getDescripcionItemC());
            }
        }
        this.cmbTipo.setSelectedIndex(0);
        this.cmbDepen.setSelectedIndex(0);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //String estado = this.cmbEstado.getSelectedItem().toString();
        String identificacion = this.txtIdent.getText();
        String nombres = this.txtNombres.getText();
        String tipo = this.cmbTipo.getSelectedItem().toString();
        String tipoInt = tipo.equals("Secretaria") ? "2" : "1";
        String dependencia = this.cmbDepen.getSelectedItem().toString();
        String pass = String.valueOf(this.txtPass.getPassword());
        String passEnc = EncripterManager.encryptKey(pass);
        //validacion campos vacios
        if (identificacion.isEmpty() || nombres.isEmpty() || tipo.isEmpty() || dependencia.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos Vacios.");
        } else {
            boolean permiteIngreso = true;
            if (totalAdmin >= 1 || totalSec >= 5) {
                permiteIngreso = false;
            }
            if (permiteIngreso) {
                Administrativo usuario = new Administrativo();
                usuario.setIntPersona((totalAdmin + totalSec) + 1);
                usuario.setStrIdentificacion(identificacion);
                usuario.setStrNombres(nombres);
                usuario.setChrTipo(tipoInt);
                usuario.setStrDependencia(dependencia);
                usuario.setPass(passEnc);
                try {
                    txtParsing1.writeDataAdministrativos(usuario);
                    txtParsing1.lstAdministrativosObj.add(usuario);
                    JOptionPane.showMessageDialog(this, "Ingreso Exitoso.");
                    this.initialize();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error.");
                    System.err.format("IOException: %s%n", ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El sistema admite como maximo 5 Scretarias y 1 Administrador");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        this.txtNombres.setText("");
        this.txtIdent.setText("");
        this.cmbTipo.setSelectedIndex(0);
        this.cmbDepen.setSelectedIndex(0);
        this.txtPass.setText("");
    }//GEN-LAST:event_btnCleanActionPerformed

    Administrativo admFind = null;
    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        tblUsers.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                // do some actions here, for example
                // print first column value from selected row
                String ci = tblUsers.getValueAt(tblUsers.getSelectedRow(), 1).toString();
                admFind = new Administrativo();
                admFind = getAdminById(ci);

                txtNombres.setText(admFind.getStrNombres());
                txtIdent.setText(admFind.getStrIdentificacion());
                Object tipo = "2".equals(admFind.getChrTipo()) ? "Secretaria" : "Administrador";
                cmbTipo.setSelectedItem(tipo);
                Object depen = admFind.getStrDependencia();
                cmbDepen.setSelectedItem(depen);
                //JOptionPane.showMessageDialog(null, tblUsers.getValueAt(tblUsers.getSelectedRow(), 0).toString());
            }
        });
    }//GEN-LAST:event_tblUsersMouseClicked

    private void btnClean1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClean1ActionPerformed
        // TODO add your handling code here:
        if (admFind == null) {
            JOptionPane.showMessageDialog(null, "Selecciona un usuario a actualizar!");
        } else {
            //Buscar en lista y actulizar el usuario
            int index = getAdminByIdNum(admFind.getStrIdentificacion());
            //Actulizar de la lista recogiendo valores nuevos

            String identificacion = this.txtIdent.getText();
            String nombres = this.txtNombres.getText();
            String tipo = this.cmbTipo.getSelectedItem().toString();
            String tipoInt = tipo.equals("Secretaria") ? "2" : "1";
            String dependencia = this.cmbDepen.getSelectedItem().toString();
            String pass = String.valueOf(this.txtPass.getPassword());
            String passEnc = EncripterManager.encryptKey(pass);

            Administrativo admNew = new Administrativo();
            admNew.setIntPersona((totalAdmin + totalSec) + 1);
            admNew.setStrIdentificacion(identificacion);
            admNew.setStrNombres(nombres);
            admNew.setChrTipo(tipoInt);
            admNew.setStrDependencia(dependencia);
            admNew.setPass(passEnc);

            txtParsing1.lstAdministrativosObj.set(index, admNew);
            this.initialize();
            JOptionPane.showMessageDialog(this, "Actualizacion Exitosa.");
        }
    }//GEN-LAST:event_btnClean1ActionPerformed

    private void btnClean2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClean2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClean2ActionPerformed

    public Administrativo getAdminById(String ci) {
        for (Administrativo adm : txtParsing1.lstAdministrativosObj) {
            if (adm.getStrIdentificacion().equals(ci)) {
                return adm;
            }
        }
        return null;
    }

    public int getAdminByIdNum(String ci) {
        int i = 0;
        for (Administrativo adm : txtParsing1.lstAdministrativosObj) {
            if (adm.getStrIdentificacion().equals(ci)) {
                return i;
            }
            i++;
        }
        return i;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnClean1;
    private javax.swing.JButton btnClean2;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbDepen;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescCat;
    private javax.swing.JLabel lblDescCat1;
    private javax.swing.JLabel lblDescCat2;
    private javax.swing.JLabel lblDescCat3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtIdent;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
